// ./src/app/layout.tsx
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";

import NavbarComp from "@/my_utils/Navbar";
import Footer from "@/my_utils/Footer";
import { UserProvider, useUser } from "@/userContext";
import axios from "axios";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });
const pop = Poppins({ weight: "400", subsets: ["latin"] });

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="md:dark dark">
            <body className={pop.className}>
                <UserProvider>
                    <NavbarComp />
                    <div>{children}</div>
                    <Footer />
                </UserProvider>
            </body>
        </html>
    );
}

// Exporting metadata separately
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
